CREATE DATABASE IF NOT EXISTS `community` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci */;
USE `community`;
DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
    `id`          bigint(20) unsigned NOT NULL AUTO_INCREMENT,
    `name`        varchar(128)        NOT NULL DEFAULT '',
    `avatar`      varchar(128)        NOT NULL DEFAULT '',
    `password`    varchar(16)         NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

/* Users are generated by ChatGPT */
INSERT INTO `user` (`name`, `avatar`, `password`) VALUES
    ('Alice', 'alice.jpg', 'p@ssw0rd'),
    ('Bob', 'bob.jpg', 'securepw'),
    ('Charlie', 'charlie.jpg', 'mysecret'),
    ('David', 'david.jpg', 'david123'),
    ('Eve', 'eve.jpg', 'eve456'),
    ('Frank', 'frank.jpg', 'frankpass'),
    ('Grace', 'grace.jpg', 'gracepass'),
    ('Helen', 'helen.jpg', 'helen987'),
    ('Ivy', 'ivy.jpg', 'ivy@321'),
    ('Jack', 'jack.jpg', 'jack567');
